@Library('jenkins-shared-library') _
pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                myBuild()
            }
        }

        stage('Deploy') {
            steps {
                myDeploy("service1")
            }
        }
    }

    post {
        always {
            myNotify("Service1 pipeline completed")
        }
    }
}
