@Library('jenkins-shared-library') _
pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo "Running build for Service B"
                myBuild()
            }
        }

        stage('Deploy') {
            steps {
                myDeploy("service2")
            }
        }
    }

    post {
        always {
            myNotify("Service B pipeline completed")
        }
    }
}

